module.exports = {
  Config: {
    timezone: 'Asia/Shanghai',
    siteName: '看点网',
    cookieSecret: '#$%nnja5720',
    salt: '#$%%^^^',
    port: 8888,
    interval: 1000 * 60 * 20,
    staticMaxAge: 3600000 * 24 * 1,
    limit: 15,
    hotQty: 4,
    maxRssItems: 50,
    crawlFlag: 0, // 0: only one or few pages; 1: all pages
    qqTags: {
      '留声机': 'qq_news_lsj',
      //'讲武堂': 'qq_news_jwt',
      '西洋镜': 'qq_news_xyj',
      '问编辑': 'qq_news_wbj',
      '新闻周考': 'qq_news_xwzk',
      //'新闻哥': 'qq_news_xwg',
      //'找亮点': 'qq_news_zld',
      '猜新闻': 'qq_news_cxw',
      //'话题': 'qq_news_ht',
      '数据控': 'qq_news_sjk',
      '视界': 'qq_news_sj',
      '娱乐一周精选': 'qq_photo_ylyzjx',
      '一周图片精选': 'qq_photo_yztpjx',
      '脸谱': 'qq_photo_lp',
      //'图话': 'qq_photo_th',
      //'存照': 'qq_photo_cz',
      '去年今日': 'qq_photo_lp',
      '影像记忆': 'qq_photo_yxjy',
      '凡人观时尚': 'qq_news_frgss',
      '新闻当事人': 'qq_news_xwdsr',
      //'科技不怕问': 'qq_news_kjbpw',
      //'中国人的一天': 'qq_photo_zgrdyt',
    },
  },
};