module.exports = {
  Config: {
    timezone: 'Asia/Shanghai',
    siteName: '看点网',
    cookieSecret: '#$%nnja5720',
    salt: '#$%%^^^',
    port: 8888,
    interval: 1000 * 60 * 20,
    staticMaxAge: 3600000 * 24 * 1,
    limit: 15,
    hotQty: 4,
    maxRssItems: 50,
    sohuTags: {
      '先知道': '681',
      '神吐槽': '682',
      '热辣评': '683',
      '我来说两句':'915',
      '变态辣椒':'677',
      '狐揭秘': 'sohu_hjm',
      '涨姿势': 'sohu_zzs',
      '搜查科':'sohu_sck',
      '开心一刻': 'sohu_kxyk',
      '数说IT': 'sohu_shit',
      '红人红事榜': 'sohu_hrhsb',
      '快评': 'sohu_kp',
      '图粹': 'sohu_photo_455',
      '图片故事': 'sohu_photo_456',
      '爱新奇': 'sohu_photo_465',
      '明星情史': 'sohu_photo_458',
      '明星旧照': 'sohu_photo_457',
      '趣图': 'sohu_photo_459',
      '清纯美女': 'sohu_photo_460',
      /*'IQ问答':'684',
      '留几手':'671',
      '黑眼睛看世界':'672',
      '微天下':'673',
      '祖德狐说':'674',
      'CAOTV观点保真':'675',
      '司马白话':'676',
      '钛媒体':'638',
      '知乎每日精选':'416',
      '挖段子•趣图':'610',
      '挖段子•冷笑话':'533',
      '趣图集':'500',
      '捧腹网':'501',
      '来福岛':'502',
      '搞笑哦':'528',
      '萝卜网':'530',
      '对路网':'532',
      '无聊哦':'580',
      '妹子图':'581',
      '一周图': 'yzt',
      '特别策划': '4741',
      '求是': 'qs',
      '烽火组': 'fhz',
      '今日谈': 'jrt',*/
    },
    sinaTags: {
      '今日网言': 'sina_jrwy',
      '新观察': 'sina_xgc',
      '海外观察': 'sina_hwgc',
      '军情茶馆': 'sina_jqcg',
      '万花筒': 'sina_wht',
      '今日神最右': 'sina_jrszy',
      '午饭话题': 'sina_wfht',
      '午饭聊点啥': 'sina_wflds',
      '茶娱饭后': 'sina_cyfh',
      '每日深度': 'sina_mrsd',
      '毒舌美少女': 'sina_dsmsn',
    },
    qqTags: {
      '留声机': 'qq_news_lsj',
      //'讲武堂': 'qq_news_jwt',
      '西洋镜': 'qq_news_xyj',
      '问编辑': 'qq_news_wbj',
      '新闻周考': 'qq_news_xwzk',
      //'新闻哥': 'qq_news_xwg',
      //'找亮点': 'qq_news_zld',
      '猜新闻': 'qq_news_cxw',
      //'话题': 'qq_news_ht',
      '数据控': 'qq_news_sjk',
      '视界': 'qq_news_sj',
      '娱乐一周精选': 'qq_photo_ylyzjx',
      '一周图片精选': 'qq_photo_yztpjx',
      '脸谱': 'qq_photo_lp',
      //'图话': 'qq_photo_th',
      //'存照': 'qq_photo_cz',
      '去年今日': 'qq_photo_lp',
      '影像记忆': 'qq_photo_yxjy',
      '凡人观时尚': 'qq_news_frgss',
      '新闻当事人': 'qq_news_xwdsr',
      //'科技不怕问': 'qq_news_kjbpw',
      //'中国人的一天': 'qq_photo_zgrdyt',
    },
  },
};